print(all([True]))
print(all([True, True, True]))
print(all([True, False, True]))
print(all([1, 2, 5.1]))
print(all([1, 2, 5.1, 0.3, 0]))
print(all(["a", "b"]))
print(all(["a", "b", ""]))
print(all(["a", "b", " "]))

print()

print(any([True]))
print(any([True, True, True]))
print(any([True, False, True]))
print(any([False, False, False]))
print(any([1, 2, 5.1]))
print(any([1, 2, 5.1, 0.3, 0]))
print(any([ 0, 0]))
print(any(["a", "b"]))
print(any(["a", "b", ""]))
print(any([""]))
print(any(["a", "b", " "]))